### ISSUE TITLE
css variables not overrideable

### ISSUE THREAD

**Issue by ewized** [ewized/base-elements#19]
Css variables that are to be override-able need to be placed in the `:host`  not nested.

```css
// other elements can override
:host {
  --e-header-height: 50px;
}

// other elements cant override
header {
  --e-header-background: #678;
  --e-header-border: 1px solid #789;
}
```
